name: Snyk Python Scan

on: [push, pull_request]

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Snyk CLI
        run: |
          curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x ./snyk
          mv ./snyk /usr/local/bin/
      - name: Scan source code SAST
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk code test --json > snyk-code-results.json || true 
      - name: Scan iac IAC
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk iac test --report --json > snyk-iac-results.json || true
      - name: Scan dependencies SCA
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test
